system:
  dataset: 'energy'
  seq_len: 24
  lr: 1e-3
  batch_size: 128
  model_name: 'trans-time-gan'
  device: 'cuda:0'
  run_name: 'TimeGAN (research)'
  jointly_num_epochs: 50
  perplexity: 10
  step: 'embedding'

t_d:
  threshold: 0.15
  feature_size: 14
  num_layers: 8
  dropout: 0.4
  n_head: 16
  dim_output: 1

t_g:
  feature_size: 28
  num_layers: 8
  dropout: 0.1
  n_head: 16
  dim_output: 14

t_emb:
  num_epochs: 50
  feature_size: 28
  num_layers: 8
  dropout: 0.1
  n_head: 8
  dim_output: 14

t_sup:
  num_epochs: 50
  feature_size: 14
  num_layers: 8
  dropout: 0.1
  n_head: 8
  dim_output: 14

t_rec:
  feature_size: 14
  num_layers: 8
  dropout: 0.1
  n_head: 8
  dim_output: 28